server {
  listen                443 ssl;
  listen 80;
  server_name   HapiFormGuardApi.amdc.com.sg;
  keepalive_timeout   70;

  ssl_certificate       /etc/nginx/ssl/all.amdc_com_sg.pem;
  ssl_certificate_key   /etc/nginx/ssl/all.amdc_com_sg.key;


  add_header X-Robots-Tag "noindex, nofollow";


  location / {
    # proxy_pass http://unix:/usr/http/eden-crm-api-2023/eden-crm-api-2023.sock;
    proxy_pass http://localhost:8078;

    # ✅ Forward important headers
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # ✅ Forward Referer & Origin headers
    # Referer	https://bdomain.com/form.html
    # Origin	https://bdomain.com
    proxy_set_header Referer $http_referer;
    proxy_set_header Origin $http_origin;

  }

}