"""form-guard-fist init

Revision ID: 22ed611b6e46
Revises: 
Create Date: 2026-04-25 15:35:06.918123

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision = '22ed611b6e46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_rate_limit_defaults',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('form_key', sa.String(), nullable=False),
    sa.Column('limit_per_hour', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_rate_limit_defaults_form_key'), 'form_rate_limit_defaults', ['form_key'], unique=True)
    op.create_table('ip_rate_limit_overrides',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('form_key', sa.String(), nullable=True),
    sa.Column('ip_range', postgresql.CIDR(), nullable=False),
    sa.Column('limit_per_hour', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_rate_limit_overrides_form_key'), 'ip_rate_limit_overrides', ['form_key'], unique=False)
    op.create_table('submission_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('form_key', sa.String(), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_events_form_key'), 'submission_events', ['form_key'], unique=False)
    op.create_index(op.f('ix_submission_events_ip'), 'submission_events', ['ip'], unique=False)
    op.create_index(op.f('ix_submission_events_occurred_at'), 'submission_events', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_events_occurred_at'), table_name='submission_events')
    op.drop_index(op.f('ix_submission_events_ip'), table_name='submission_events')
    op.drop_index(op.f('ix_submission_events_form_key'), table_name='submission_events')
    op.drop_table('submission_events')
    op.drop_index(op.f('ix_ip_rate_limit_overrides_form_key'), table_name='ip_rate_limit_overrides')
    op.drop_table('ip_rate_limit_overrides')
    op.drop_index(op.f('ix_form_rate_limit_defaults_form_key'), table_name='form_rate_limit_defaults')
    op.drop_table('form_rate_limit_defaults')
    # ### end Alembic commands ###

