"""uq_form_key_ip_range

Revision ID: 459be6ba7c70
Revises: 22ed611b6e46
Create Date: 2026-04-25 20:52:46.027971

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '459be6ba7c70'
down_revision = '22ed611b6e46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ip_rate_limit_overrides', 'form_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('uq_form_key_ip_range', 'ip_rate_limit_overrides', ['form_key', 'ip_range'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_form_key_ip_range', 'ip_rate_limit_overrides', type_='unique')
    op.alter_column('ip_rate_limit_overrides', 'form_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###

