"""check 429 strikes

Revision ID: cef5e2294050
Revises: 459be6ba7c70
Create Date: 2026-04-26 19:31:28.086197

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision = 'cef5e2294050'
down_revision = '459be6ba7c70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_429_strikes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('form_key', sa.String(), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_key', 'ip', name='uq_form_key_ip')
    )
    op.create_index(op.f('ix_check_429_strikes_form_key'), 'check_429_strikes', ['form_key'], unique=False)
    op.create_index(op.f('ix_check_429_strikes_ip'), 'check_429_strikes', ['ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_check_429_strikes_ip'), table_name='check_429_strikes')
    op.drop_index(op.f('ix_check_429_strikes_form_key'), table_name='check_429_strikes')
    op.drop_table('check_429_strikes')
    # ### end Alembic commands ###

